#!/usr/bin/env python

links = {}

for country in ('US','CA','IN','GB','AU'):
    links[country]={}
    for category in ('general','health','science','tech','entertainment','gaming','politics','business','sports','kerala'):
        links[country][category]={}

links['US']['general']['http://feeds.abcnews.com/abcnews/usheadlines'] = 1
links['US']['general']['http://rss.cnn.com/rss/cnn_topstories.rss'] = 1
links['US']['general']['http://www.cbsnews.com/latest/rss/main'] = 1
links['US']['general']['http://www.nytimes.com/services/xml/rss/nyt/National.xml'] = 1
links['US']['general']['http://online.wsj.com/xml/rss/3_7085.xml'] = 1
links['US']['general']['http://content.usatoday.com/marketing/rss/rsstrans.aspx?feedId=news2'] = 1
links['US']['general']['http://rss.csmonitor.com/feeds/usa'] = 1
links['US']['general']['http://feeds.nbcnews.com/feeds/topstories'] = 1
links['US']['general']['http://feeds.nbcnews.com/feeds/worldnews'] = 1
links['US']['general']['http://feeds.reuters.com/Reuters/worldNews'] = 1
links['US']['general']['http://feeds.reuters.com/Reuters/domesticNews'] = 1
links['US']['general']['http://hosted.ap.org/lineups/USHEADS.rss'] = 1
links['US']['general']['http://hosted.ap.org/lineups/WORLDHEADS.rss'] = 1
links['US']['general']['http://www.huffingtonpost.com/feeds/verticals/world/index.xml'] = 1
links['US']['general']['http://feeds.bbci.co.uk/news/world/us_and_canada/rss.xml'] = 1
links['US']['general']['http://news.yahoo.com/rss/us'] = 1
links['US']['general']['http://rss.news.yahoo.com/rss/world'] = 1
links['US']['general']['http://www.newsweek.com/rss'] = 1
links['US']['general']['http://feeds.feedburner.com/thedailybeast/articles'] = 1
links['US']['general']['http://qz.com/feed'] = 1
links['US']['general']['http://www.theguardian.com/world/usa/rss'] = 1
links['US']['general']['http://www.politico.com/rss/politicopicks.xml'] = 1
links['US']['general']['http://www.newyorker.com/feed/news'] = 1
links['US']['general']['http://feeds.feedburner.com/NationPBSNewsHour'] = 1
links['US']['general']['http://feeds.feedburner.com/NewshourWorld'] = 1
links['US']['general']['http://www.usnews.com/rss/news'] = 1
links['US']['general']['http://www.npr.org/rss/rss.php?id=1003'] = 1
links['US']['general']['http://www.npr.org/rss/rss.php?id=1004'] = 1
links['US']['general']['http://feeds.feedburner.com/AtlanticNational'] = 1
links['US']['general']['http://feeds.feedburner.com/TheAtlanticWire'] = 1
links['US']['general']['http://www.latimes.com/nation/rss2.0.xml'] = 1
links['US']['general']['http://www.latimes.com/world/rss2.0.xml'] = 1
links['US']['general']['http://api.breakingnews.com/api/v1/item/?format=rss'] = 1
links['US']['general']['https://news.vice.com/rss'] = 1
links['US']['general']['http://talkingpointsmemo.com/feed/livewire'] = 1
links['US']['general']['http://www.salon.com/category/news/feed/rss/'] = 1
links['US']['general']['http://time.com/newsfeed/feed/'] = 1
links['US']['general']['http://feeds.foxnews.com/foxnews/latest?format=xml'] = 1
links['US']['general']['http://mashable.com/us-world/rss/'] = 1
links['US']['politics']['http://www.politico.com/rss/magazine.xml'] = 1
links['US']['politics']['http://www.politico.com/rss/Top10Blogs.xml'] = 1
links['US']['politics']['http://www.huffingtonpost.com/feeds/verticals/politics/index.xml'] = 1
links['US']['politics']['http://rss.cnn.com/rss/cnn_allpolitics.rss'] = 1
links['US']['politics']['http://www.buzzfeed.com/politics.xml'] = 1
links['US']['politics']['http://feeds.nbcnews.com/feeds/nbcpolitics'] = 1
links['US']['politics']['http://feeds.foxnews.com/foxnews/politics'] = 1
links['US']['politics']['http://feeds.washingtonpost.com/rss/rss_election-2012'] = 1
links['US']['politics']['http://rss.nytimes.com/services/xml/rss/nyt/Politics.xml'] = 1
links['US']['politics']['http://rss.nytimes.com/services/xml/rss/nyt/Upshot.xml'] = 1
links['US']['politics']['http://thecaucus.blogs.nytimes.com/feed/'] = 1
links['US']['politics']['http://feeds.reuters.com/Reuters/PoliticsNews'] = 1
links['US']['politics']['http://blogs.wsj.com/washwire/feed/?mod=WSJ_Politics%2520and%2520Policy'] = 1
links['US']['politics']['http://www.reddit.com/r/politics/.rss'] = 1
links['US']['politics']['http://feeds.dailykos.com/dailykos/index.xml'] = 1
links['US']['politics']['http://www.npr.org/rss/rss.php?id=1014'] = 1
links['US']['politics']['http://www.npr.org/rss/rss.php?id=5'] = 1
links['US']['politics']['http://www.rollcall.com/rss/all_news.xml'] = 1
links['US']['politics']['http://www.rollcall.com/news/?zkDo=showRSS'] = 1
links['US']['politics']['http://www.rollcall.com/politics/archives/?zkDo=showRSS'] = 1
links['US']['politics']['http://www.rollcall.com/policy/archives/?zkDo=showRSS'] = 1
links['US']['politics']['http://www.nationaljournal.com/?rss=1'] = 1
links['US']['politics']['http://www.nationaljournal.com/white-house?rss=1'] = 1
links['US']['politics']['http://www.nationaljournal.com/congress?rss=1'] = 1
links['US']['politics']['http://www.nationaljournal.com/politics?rss=1'] = 1
links['US']['politics']['http://www.nationaljournal.com/congressional-connection?rss=1'] = 1
links['US']['politics']['http://www.thenation.com/rss/articles'] = 1
links['US']['politics']['http://www.thenation.com/blogs/rss/politics'] = 1
links['US']['politics']['http://www.thenation.com/blogs/rss/foreign-reporting'] = 1
links['US']['politics']['http://www.washingtontimes.com/rss/headlines/news/politics/'] = 1
links['US']['politics']['http://feeds.feedburner.com/realclearpolitics/qlMj'] = 1
links['US']['politics']['http://feeds.feedburner.com/BreitbartFeed'] = 1
links['US']['politics']['http://dailycaller.com/section/politics/feed/'] = 1
links['US']['politics']['https://www.nationalreview.com/rss.xml'] = 1
links['US']['politics']['http://feeds.feedburner.com/DrudgeReportFeed'] = 1
links['US']['politics']['http://www.weeklystandard.com/rss/site.xml'] = 1
links['US']['politics']['http://www.usnews.com/blogrss/washington-whispers'] = 1
links['US']['politics']['http://www.usnews.com/blogrss/Ken-Walshs-Washington'] = 1
links['US']['politics']['http://www.usnews.com/blogrss/ballot-2014'] = 1
links['US']['politics']['http://feeds.slate.com/slate-101526'] = 1
links['US']['politics']['http://feeds.feedburner.com/motherjones/Politics'] = 1
links['US']['politics']['http://www.newrepublic.com/taxonomy/term/17538/feed'] = 1
links['US']['politics']['http://fivethirtyeight.com/politics/feed/'] = 1
links['US']['politics']['http://www.redstate.com/feed/'] = 1
links['US']['politics']['http://humanevents.com/feed/'] = 1
links['US']['politics']['http://twitchy.com/category/us-politics/feed/'] = 1
links['US']['politics']['http://talkingpointsmemo.com/feed/all'] = 1
links['US']['business']['http://hosted2.ap.org/atom/APDEFAULT/f70471f764144b2fab526d39972d37b3'] = 1
links['US']['business']['http://online.wsj.com/xml/rss/3_7014.xml'] = 1
links['US']['business']['http://www.nytimes.com/services/xml/rss/nyt/Business.xml'] = 1
links['US']['business']['http://rss.nytimes.com/services/xml/rss/nyt/Business.xml'] = 1
links['US']['business']['http://feeds.reuters.com/reuters/businessNews'] = 1
links['US']['business']['http://feeds.washingtonpost.com/rss/rss_storyline'] = 1
links['US']['business']['http://feeds.washingtonpost.com/rss/rss_wonkblog'] = 1
links['US']['business']['http://www.economist.com/feeds/print-sections/77/business.xml'] = 1
links['US']['business']['http://www.business-standard.com/rss/latest.rss'] = 1
links['US']['business']['http://www.business-standard.com/rss/home_page_top_stories.rss'] = 1
links['US']['business']['http://feeds.harvardbusiness.org/harvardbusiness?format=xml'] = 1
links['US']['business']['http://au.ibtimes.com/rss/articles/region/1.rss'] = 1
links['US']['business']['http://www.businessweek.com/search/rssfeed.htm'] = 1
links['US']['business']['http://www.huffingtonpost.com/feeds/verticals/business/news.xml'] = 1
links['US']['business']['http://www.ft.com/rss/home/us'] = 1
links['US']['business']['http://rss.cnn.com/rss/edition_business.rss'] = 1
links['US']['business']['http://www.bloomberg.com/feed/podcast/law.xml'] = 1
links['US']['health']['http://www.health.harvard.edu/rss.php'] = 1
links['US']['health']['http://www.health.com/health/healthy-happy/feed'] = 1
links['US']['health']['http://rss.cnn.com/rss/cnn_health.rss'] = 1
links['US']['health']['http://www.nytimes.com/services/xml/rss/nyt/Health.xml'] = 1
links['US']['health']['http://www.forbes.com/health/feed2/'] = 1
links['US']['health']['http://feeds.bbci.co.uk/news/health/rss.xml?edition=us'] = 1
links['US']['health']['http://feeds.abcnews.com/abcnews/healthheadlines'] = 1
links['US']['health']['http://feeds.nbcnews.com/feeds/health'] = 1
links['US']['health']['http://feeds.reuters.com/reuters/healthNews'] = 1
links['US']['health']['http://www.chicagotribune.com/lifestyles/health/rss2.0.xml'] = 1
links['US']['health']['http://feeds.huffingtonpost.com/c/35496/f/677071/index.rss'] = 1
links['US']['health']['http://www.theguardian.com/society/health/rss'] = 1
links['US']['health']['http://www.nydailynews.com/lifestyle/health/index_rss.xml'] = 1
links['US']['health']['http://www.menshealth.com/events-promotions/washpofeed'] = 1
links['US']['health']['http://feeds.glamour.com/glamour/health_fitness'] = 1
links['US']['health']['http://feeds.newscientist.com/health'] = 1
links['US']['health']['http://time.com/health/feed/'] = 1
links['US']['health']['http://hosted2.ap.org/atom/APDEFAULT/bbd825583c8542898e6fa7d440b9febc'] = 1
links['US']['health']['http://www.womenshealthandfitness.com.au/component/obrss/women-s-health-fitnesscombined-feed'] = 1
links['US']['health']['http://www.usnews.com/rss/health?int=a7fe09'] = 1
links['US']['health']['http://news.yahoo.com/rss/health'] = 1
links['US']['health']['http://www.wsj.com/xml/rss/3_7201.xml'] = 1
links['US']['health']['http://www.healthcareitnews.com/home/feed'] = 1
links['US']['health']['http://www.modernhealthcare.com/section/rss01&mime=xml'] = 1
links['US']['health']['http://www.mayoclinic.org/rss/all-health-information-topics'] = 1
links['US']['health']['http://feeds.sciencedaily.com/sciencedaily/top_news/top_health'] = 1
links['US']['health']['http://khn.org/feed/'] = 1
links['US']['health']['http://feeds.lexblog.com/foodsafetynews/mRcs'] = 1
links['US']['health']['http://feeds.washingtonpost.com/rss/lifestyle'] = 1
links['US']['health']['http://www.buzzfeed.com/health.xml'] = 1
links['US']['health']['http://vitals.lifehacker.com/rss'] = 1
links['US']['health']['http://www.self.com/feed/fitness-news/'] = 1
links['US']['health']['http://feeds.huffingtonpost.com/c/35496/f/677070/index.rss'] = 1
links['US']['health']['http://www.cpsc.gov/en/Newsroom/CPSC-RSS-Feed/Recalls-RSS/'] = 1
links['US']['health']['http://www.cpsc.gov/en/Newsroom/CPSC-RSS-Feed/Recalls-RSS/'] = 1
links['US']['health']['http://www.medpagetoday.com/rss/Headlines.xml'] = 1
links['US']['health']['http://www.medscape.com/cx/rssfeeds/2700.xml'] = 1
links['US']['health']['http://rss.nytimes.com/services/xml/rss/nyt/Health.xml'] = 1
links['US']['health']['http://www.theguardian.com/lifeandstyle/health-and-wellbeing/rss'] = 1
links['US']['health']['http://rss.medicalnewstoday.com/featurednews.xml'] = 1
links['US']['health']['http://www.npr.org/rss/rss.php?id=1128'] = 1
links['US']['science']['http://www.huffingtonpost.com/feeds/verticals/science/index.xml'] = 1
links['US']['science']['http://rss.nytimes.com/services/xml/rss/nyt/Science.xml'] = 1
links['US']['science']['http://rss.nytimes.com/services/xml/rss/nyt/Space.xml'] = 1
links['US']['science']['http://feeds.foxnews.com/foxnews/science'] = 1
links['US']['science']['http://feeds.nbcnews.com/feeds/science'] = 1
links['US']['science']['http://rss.sciam.com/ScientificAmerican-Global'] = 1
links['US']['science']['http://feeds.feedburner.com/BreakingScienceNews?format=xml'] = 1
links['US']['science']['http://feeds.wired.com/wiredscience'] = 1
links['US']['science']['http://feeds.sciencedaily.com/sciencedaily'] = 1
links['US']['science']['http://www.latimes.com/health/rss2.0.xml'] = 1
links['US']['science']['http://www.chron.com/rss/feed/AP-Technology-and-Science-266.php'] = 1
links['US']['science']['http://feeds.washingtonpost.com/rss/rss_speaking-of-science'] = 1
links['US']['science']['http://www.sciencemag.org/rss/current.xml'] = 1
links['US']['science']['http://feeds.feedburner.com/DiscoverTopStories'] = 1
links['US']['science']['http://feeds.bbci.co.uk/news/science_and_environment/rss.xml'] = 1
links['US']['science']['http://feeds.howtogeek.com/howtogeek'] = 1
links['US']['science']['http://syndication.howstuffworks.com/rss/science'] = 1
links['US']['science']['http://www.npr.org/templates/rss/podlayer.php?id=1007'] = 1
links['US']['science']['http://www.nasa.gov/rss/dyn/breaking_news.rss'] = 1
links['US']['science']['http://www.livescience.com/home/feed/site.xml'] = 1
links['US']['science']['http://rss.sciam.com/ScientificAmerican-News'] = 1
links['US']['science']['http://feeds.nature.com/nbt/rss/current'] = 1
links['US']['science']['http://www.popsci.com/rss.xml'] = 1
links['US']['science']['http://nautil.us/rss/all'] = 1
links['US']['science']['http://feeds.arstechnica.com/arstechnica/science'] = 1
links['US']['science']['http://www.smithsonianmag.com/rss/science-nature/'] = 1
links['US']['science']['http://feeds.gawker.com/io9/full#_ga=1.239815749.772722176.1436906624'] = 1
links['US']['science']['http://feeds.newscientist.com/science-news'] = 1
links['US']['science']['http://feeds.newscientist.com/space'] = 1
links['US']['science']['http://www.pnas.org/rss/Feature_Article.xml'] = 1
links['US']['science']['http://www.treehugger.com/feeds/category/science/'] = 1
links['US']['science']['http://feeds2.feedburner.com/time/scienceandhealth'] = 1
links['US']['science']['http://www.eurekalert.org/rss.xml'] = 1
links['US']['science']['http://phys.org/rss-feed/'] = 1
links['US']['science']['http://rss.csmonitor.com/feeds/science'] = 1
links['US']['science']['http://news.yahoo.com/rss/science'] = 1
links['US']['science']['http://hosted2.ap.org/atom/APDEFAULT/b2f0ca3a594644ee9e50a8ec4ce2d6de'] = 1
links['US']['science']['http://omnifeed.com/feed/www.iflscience.com/rss.xml'] = 1
links['US']['science']['http://news.nationalgeographic.com/rss/index.rss'] = 1
links['US']['science']['http://www.wired.com/category/science/science-blogs/feed/'] = 1
links['US']['science']['http://feeds.reuters.com/reuters/scienceNews'] = 1
links['US']['science']['http://feeds.feedburner.com/IeeeSpectrumFullText'] = 1
links['US']['science']['http://www.theverge.com/science/rss/index.xml'] = 1
links['US']['science']['http://grist.org/feed/'] = 1
links['US']['science']['http://www.theguardian.com/science/rss'] = 1
links['US']['science']['http://www.theguardian.com/us/environment/rss'] = 1
links['US']['science']['http://feeds.sciencedaily.com/sciencedaily'] = 1
links['US']['science']['http://www.viralnova.com/feed'] = 1
links['US']['sports']['http://rss.nytimes.com/services/xml/rss/nyt/Sports.xml'] = 1
links['US']['sports']['http://www.buzzfeed.com/sports.xml'] = 1
links['US']['sports']['http://feeds.foxnews.com/foxnews/sports'] = 1
links['US']['sports']['http://feeds.sbnation.com/rss/streams'] = 1
links['US']['sports']['http://sports.espn.go.com/espn/rss/news'] = 1
links['US']['sports']['http://www.latimes.com/sports/rss2.0.xml'] = 1
links['US']['sports']['http://www.cbssports.com/partners/feeds/rss/home_news'] = 1
links['US']['sports']['http://www.si.com/rss/si_topstories.rss'] = 1
links['US']['sports']['http://feeds.gawker.com/deadspin/full'] = 1
links['US']['sports']['https://sports.yahoo.com/top/rss.xml'] = 1
links['US']['sports']['http://content.usatoday.com/marketing/rss/rsstrans.aspx?feedId=sports1'] = 1
links['US']['sports']['http://feeds.washingtonpost.com/rss/rss_early-lead'] = 1
links['US']['sports']['http://www.theguardian.com/sport/us-sport/rss'] = 1
links['US']['sports']['http://hosted.ap.org/lineups/SPORTSHEADS.rss?SITE=AP&SECTION=HOME'] = 1
links['US']['tech']['http://www.huffingtonpost.com/feeds/verticals/technology/news.xml'] = 1
links['US']['tech']['http://rss.cnn.com/rss/cnn_tech.rss'] = 1
links['US']['tech']['http://rss.nytimes.com/services/xml/rss/nyt/Technology.xml'] = 1
links['US']['tech']['http://feeds.foxnews.com/foxnews/tech'] = 1
links['US']['tech']['http://www.theverge.com/rss/group/features/index.xml'] = 1
links['US']['tech']['http://feeds.feedburner.com/TechCrunch/'] = 1
links['US']['tech']['http://feeds.wired.com/wired/index'] = 1
links['US']['tech']['http://mashable.com/category/rss/'] = 1
links['US']['tech']['http://www.cnet.com/rss/news/'] = 1
links['US']['tech']['http://www.cnet.com/rss/iphone-update/'] = 1
links['US']['tech']['http://www.cnet.com/rss/android-update/'] = 1
links['US']['tech']['http://online.wsj.com/xml/rss/3_7455.xml'] = 1
links['US']['tech']['http://www.npr.org/rss/rss.php?id=1019'] = 1
links['US']['tech']['http://www.macworld.com/index.rss'] = 1
links['US']['tech']['http://www.pcworld.com/index.rss'] = 1
links['US']['tech']['http://recode.net/category/general/feed/'] = 1
links['US']['tech']['http://recode.net/category/mobile/feed/'] = 1
links['US']['tech']['http://recode.net/category/security/feed/'] = 1
links['US']['tech']['http://recode.net/category/enterprise/feed/'] = 1
links['US']['tech']['http://www.engadget.com/rss.xml'] = 1
links['US']['tech']['http://feeds.gawker.com/gizmodo/full'] = 1
links['US']['tech']['http://feeds.feedburner.com/techcrunch/startups?format=xml'] = 1
links['US']['tech']['http://feeds.feedburner.com/TechCrunch/Gaming?format=xml'] = 1
links['US']['tech']['http://feeds.venturebeat.com/VentureBeat'] = 1
links['US']['tech']['http://feeds.venturebeat.com/smallbiz'] = 1
links['US']['tech']['http://feeds.gawker.com/valleywag/full'] = 1
links['US']['tech']['http://www.latimes.com/business/technology/rss2.0.xml'] = 1
links['US']['tech']['http://feeds.bizjournals.com/industry_7'] = 1
links['US']['tech']['http://feeds.abcnews.com/abcnews/technologyheadlines'] = 1
links['US']['tech']['http://www.buzzfeed.com/tech.xml'] = 1
links['US']['tech']['http://feeds.webservice.techradar.com/us/rss/new'] = 1
links['US']['tech']['http://gigaom.com/feed/'] = 1
links['US']['tech']['http://feeds.arstechnica.com/arstechnica/gadgets'] = 1
links['US']['tech']['http://www.geek.com/feed/'] = 1
links['US']['tech']['http://feeds.reuters.com/reuters/technologyNews?format=xml'] = 1
links['US']['tech']['http://www.computerweekly.com/rss/All-Computer-Weekly-content.xml'] = 1
links['US']['tech']['http://techrepublic.com.feedsportal.com/c/35463/f/670841/index.rss'] = 1
links['US']['tech']['http://zdnet.com.feedsportal.com/c/35462/f/675634/index.rss'] = 1
links['US']['tech']['http://www.forbes.com/technology/feed/'] = 1
links['US']['tech']['http://time.com/tech/feed/'] = 1
links['US']['tech']['http://rss.feedsportal.com/c/270/f/3547/index.rss'] = 1
links['US']['tech']['http://rssfeeds.usatoday.com/usatoday-TechTopStories'] = 1
links['US']['tech']['http://feeds.bbci.co.uk/news/technology/rss.xml'] = 1
links['US']['tech']['http://www.theinquirer.net/feeds/rss'] = 1
links['US']['tech']['http://techreport.com/news.rss'] = 1
links['US']['tech']['http://www.techspot.com/backend.xml'] = 1
links['US']['tech']['http://www.techtarget.com/html/pr/tt_pr.xml'] = 1
links['US']['tech']['http://feeds.feedburner.com/geekologie/iShm'] = 1
links['US']['tech']['http://www.dailytech.com/rss.aspx'] = 1
links['US']['tech']['http://www.digitaltrends.com/feed/'] = 1
links['US']['tech']['http://feeds2.feedburner.com/bit-tech/all'] = 1
links['US']['tech']['http://www.wsj.com/xml/rss/3_7455.xml'] = 1
links['US']['tech']['http://feeds.arstechnica.com/arstechnica/technology-lab'] = 1
links['US']['tech']['http://feeds.arstechnica.com/arstechnica/gadgets'] = 1
links['US']['tech']['http://feeds.arstechnica.com/arstechnica/business'] = 1
links['US']['tech']['http://www.informationweek.com/rss_simple.asp'] = 1
links['US']['tech']['http://feeds.newscientist.com/tech'] = 1
links['US']['tech']['http://feeds.nature.com/news/rss/news_s16'] = 1
links['US']['tech']['http://www.technologyreview.com/stream/rss/'] = 1
links['US']['tech']['http://hosted2.ap.org/atom/APDEFAULT/495d344a0d10421e9baa8ee77029cfbd'] = 1
links['US']['tech']['http://feeds.sciencedaily.com/sciencedaily/top_news/top_health'] = 1
links['US']['tech']['http://feeds.washingtonpost.com/rss/business/technology'] = 1
links['US']['tech']['http://www.techinsider.io/rss'] = 1
links['US']['tech']['http://feeds.feedburner.com/IeeeSpectrumRoboticsChannel'] = 1
links['US']['tech']['http://www.theverge.com/tech/rss/index.xml'] = 1
links['US']['tech']['http://recode.net/feed/'] = 1
links['US']['entertainment']['http://blogs.wsj.com/speakeasy/feed/'] = 1
links['US']['entertainment']['http://www.mtv.com/rss/news/news_full.jhtml'] = 1
links['US']['entertainment']['http://www.hollywoodreporter.com/blogs/live-feed/rss'] = 1
links['US']['entertainment']['http://variety.com/feed/'] = 1
links['US']['entertainment']['http://www.rollingstone.com/news.rss'] = 1
links['US']['entertainment']['http://rss.ew.com/web/ew/rss/todayslatest/index.xml'] = 1
links['US']['entertainment']['http://grantland.com/hollywood-prospectus/feed/'] = 1
links['US']['entertainment']['http://www.latimes.com/entertainment/rss2.0.xml'] = 1
links['US']['entertainment']['http://feeds.feedburner.com/nymag/vulture'] = 1
links['US']['entertainment']['http://www.newyorker.com/feed/culture'] = 1
links['US']['entertainment']['http://www.buzzfeed.com/tvandmovies.xml'] = 1
links['US']['entertainment']['http://rssfeeds.usatoday.com/usatoday-LifeTopStories'] = 1
links['US']['entertainment']['http://feeds.accesshollywood.com/AccessHollywood/LatestNews'] = 1
links['US']['entertainment']['http://feeds.feedburner.com/fuse/latest'] = 1
links['US']['entertainment']['http://www.tmz.com/rss.xml'] = 1
links['US']['entertainment']['http://www.cbsnews.com/latest/rss/entertainment'] = 1
links['US']['entertainment']['http://feeds.abcnews.com/abcnews/entertainmentheadlines'] = 1
links['US']['entertainment']['http://feeds.feedburner.com/nydnrss/entertainment'] = 1
links['US']['entertainment']['http://www.huffingtonpost.com/feeds/verticals/entertainment/index.xml'] = 1
links['US']['entertainment']['http://www.vice.com/music/rss'] = 1
links['US']['entertainment']['http://deadline.com/feed/'] = 1
links['US']['entertainment']['http://feeds.feedburner.com/EtsBreakingNews'] = 1
links['US']['entertainment']['http://feeds.nbcnews.com/feeds/todayentertainment'] = 1
links['US']['entertainment']['http://rss.cnn.com/rss/cnn_showbiz.rss'] = 1
links['US']['entertainment']['http://feeds.bet.com/AllBetcom'] = 1
links['US']['entertainment']['http://www.popsugar.com/feed'] = 1
links['US']['entertainment']['http://feed2.hollywood.com/hollywood/RhHn'] = 1
links['US']['entertainment']['http://www.hitfix.com/headlines.rss'] = 1
links['US']['entertainment']['http://rss.people.com/web/people/rss/topheadlines/index.xml'] = 1
links['US']['entertainment']['http://www.esquire.com/blogs/culture/culture-rss'] = 1
links['US']['entertainment']['http://www.usmagazine.com/feeds/movies_tv_music/atom'] = 1
links['US']['entertainment']['http://feeds2.feedburner.com/nmecom/rss/newsxml'] = 1
links['US']['entertainment']['http://news.yahoo.com/rss/entertainment'] = 1
links['US']['entertainment']['http://www.washingtonpost.com/rss/entertainment'] = 1
links['US']['entertainment']['http://feeds.reuters.com/reuters/entertainment'] = 1
links['US']['gaming']['http://feeds.ign.com/ign/all'] = 1
links['US']['gaming']['http://feeds.gawker.com/kotaku/full#_ga=1.111114893.94307673.1446233598'] = 1
links['US']['gaming']['http://feeds.feedburner.com/RockPaperShotgun'] = 1
links['US']['gaming']['http://feeds.feedburner.com/VGChartz'] = 1
links['US']['gaming']['http://toucharcade.com/feed/'] = 1
links['US']['gaming']['http://killscreendaily.com/articles/latest/'] = 1
links['US']['gaming']['http://www.engadget.com/tag/@gaming/rss.xml'] = 1
links['US']['gaming']['http://fulltextrssfeed.com/feed.php?url=www.joystiq.com%2Frss.xml'] = 1
links['US']['gaming']['http://www.gamesindustry.biz/rss/gamesindustry_news_feed.rss'] = 1
links['US']['gaming']['http://www.giantbomb.com/feeds/mashup/'] = 1
links['US']['gaming']['http://www.gamespot.com/feeds/mashup/'] = 1
links['US']['gaming']['http://www.pcworld.com/column/game-on/index.rss'] = 1
links['US']['gaming']['http://gamepolitics.com/feed/'] = 1
links['US']['gaming']['http://www.gamasutra.com/static2/rssfeeds.html'] = 1
links['US']['gaming']['http://www.eurogamer.net/?format=rss'] = 1
links['US']['gaming']['http://rss.escapistmagazine.com/tags/video-games.xml'] = 1
links['US']['gaming']['http://www.destructoid.com/?mode=atom'] = 1
links['US']['gaming']['https://www.cheapassgamer.com/rss/forums/1-cheap-ass-gamer-video-game-dealsforum/'] = 1
links['US']['gaming']['http://www.gametrailers.com/about/rss'] = 1
links['US']['gaming']['http://feeds.feedburner.com/Rpgcast'] = 1
links['US']['gaming']['http://www.tigsource.com/feed/'] = 1
links['US']['gaming']['http://www.pocketgamer.co.uk/rss.asp'] = 1
links['US']['gaming']['http://www.polygon.com/rss/index.xml'] = 1
links['US']['gaming']['http://www.gamesradar.com/all-platforms/news/rss/'] = 1
links['US']['gaming']['http://feeds.feedburner.com/TechCrunch/gaming'] = 1
links['US']['gaming']['http://www.wired.com/category/underwire/feed/'] = 1
links['US']['gaming']['http://www.cnet.com/rss/gaming/'] = 1
links['US']['gaming']['http://feeds.webservice.techradar.com/us/rss/news/gaming'] = 1
links['US']['gaming']['http://rssfeeds.usatoday.com/topgaming'] = 1
links['US']['gaming']['http://feeds.arstechnica.com/arstechnica/gaming'] = 1
links['CA']['general']['http://rss.canada.com/get/?F7497'] = 1
links['CA']['general']['http://news.gc.ca/web/fd-en.do?mthd=ntnl&ft=atom'] = 1
links['CA']['general']['http://news.gc.ca/web/fd-en.do?mthd=rgnl&ft=atom'] = 1
links['CA']['general']['http://www.journaldemontreal.com/rss.xml'] = 1
links['CA']['general']['http://rss.radio-canada.ca/fils/nouvelles/national.xml'] = 1
links['CA']['general']['http://www.calgarysun.com/home/rss.xml'] = 1
links['CA']['general']['http://leaderpost.com/feed/'] = 1
links['CA']['general']['http://thestarphoenix.com/feed/'] = 1
links['CA']['general']['http://windsorstar.com/feed/'] = 1
links['CA']['general']['http://www.cbc.ca/cmlink/rss-canada'] = 1
links['CA']['general']['http://www.ctvnews.ca/rss/ctvnews-ca-canada-public-rss-1.822284'] = 1
links['CA']['general']['http://rss.canada.com/get/?F75'] = 1
links['CA']['general']['http://globalnews.ca/canada/feed/'] = 1
links['CA']['general']['http://www.thestar.com/feeds.articles.news.canada.rss'] = 1
links['CA']['general']['http://www.theglobeandmail.com/news/national/?service=rss'] = 1
links['CA']['general']['http://feeds.bbci.co.uk/news/world/us_and_canada/rss.xml'] = 1
links['CA']['general']['http://rss.canada.com/get/?F270'] = 1
links['CA']['general']['http://www.macleans.ca/feed/'] = 1
links['CA']['general']['http://rss.canada.com/get/?F7364'] = 1
links['CA']['general']['http://rss.canada.com/get/?F264'] = 1
links['CA']['general']['http://www.nhl.com/rss/news.xml'] = 1
links['CA']['general']['http://feeds.reuters.com/Reuters/worldNews'] = 1
links['CA']['general']['http://www.660news.com/featured/spotlight/feed/'] = 1
links['CA']['general']['http://www.brandonsun.com/rss/?path=%2Fnational%2Fbreaking-news'] = 1
links['CA']['general']['http://thewalrus.ca/feed/'] = 1
links['CA']['general']['http://www.torontosun.com/home/rss.xml'] = 1
links['CA']['general']['http://rss.canada.com/get/?F243'] = 1
links['CA']['general']['http://rss.canada.com/get/?F259'] = 1
links['CA']['general']['http://rss.canada.com/get/?F291'] = 1
links['CA']['general']['http://feeds.feedblitz.com/thetyee'] = 1
links['CA']['politics']['http://www.huffingtonpost.ca/feeds/verticals/canada-politics/index.xml'] = 1
links['CA']['politics']['http://backofthebook.ca/feed/rss/'] = 1
links['CA']['politics']['http://rss.radio-canada.ca/fils/nouvelles/politique.xml'] = 1
links['CA']['politics']['http://feeds.feedburner.com/rabble-news?format=xml'] = 1
links['CA']['politics']['http://www.hilltimes.com/feed'] = 1
links['CA']['politics']['http://www.theglobeandmail.com/news/politics/?service=rss'] = 1
links['CA']['politics']['http://rss.cbc.ca/lineup/politics.xml'] = 1
links['CA']['politics']['http://www.ctvnews.ca/rss/ctvnews-ca-politics-public-rss-1.822302'] = 1
links['CA']['politics']['http://globalnews.ca/politics/feed/'] = 1
links['CA']['politics']['http://globalnews.ca/politics/feed/'] = 1
links['CA']['politics']['http://www.economist.com/topics/canadian-politics/index.xml'] = 1
links['CA']['politics']['http://www.thestar.com/feeds.blogs.news.politics_blog.rss'] = 1
links['CA']['politics']['http://www.thestar.com/feeds.articles.news.canada.rss'] = 1
links['CA']['politics']['http://www.macleans.ca/author/inklesswells/feed/'] = 1
links['CA']['politics']['http://topics.nytimes.com/top/news/international/countriesandterritories/canada/index.html?rss=1'] = 1
links['CA']['business']['http://rss.canada.com/get/?F7537'] = 1
links['CA']['business']['http://feeds.feedburner.com/morningstar/glkd'] = 1
links['CA']['business']['http://news.gc.ca/web/fd-en.do?mthd=thm&ft=atom&crtr.thm1D=7'] = 1
links['CA']['business']['http://news.gc.ca/web/fd-en.do?mthd=thm&ft=atom&crtr.thm1D=17'] = 1
links['CA']['business']['http://rss.radio-canada.ca/fils/nouvelles/economieaffaires.xml'] = 1
links['CA']['business']['http://www.calgarysun.com/money/rss.xml'] = 1
links['CA']['business']['http://www.huffingtonpost.ca/feeds/verticals/canada-business/index.xml'] = 1
links['CA']['business']['http://rss.canoe.com/Money/home.xml'] = 1
links['CA']['business']['http://www.itbusiness.ca/feed'] = 1
links['CA']['business']['http://www.ft.com/rss/home/us'] = 1
links['CA']['business']['http://rss.cbc.ca/lineup/business.xml'] = 1
links['CA']['business']['http://www.cbj.ca/business_news/canadian_business_news/index.1.rss'] = 1
links['CA']['business']['http://www.cbj.ca/business_in_action/april_11/index.1.rss'] = 1
links['CA']['business']['http://feeds.feedburner.com/FP_TopStories?format=xml'] = 1
links['CA']['business']['http://www.canadianbusiness.com/feed/'] = 1
links['CA']['business']['http://www.ctvnews.ca/rss/business/ctv-news-business-headlines-1.867648'] = 1
links['CA']['business']['http://www.economist.com/blogs/americasview/2014/09/politics-alberta?fsrc=rss'] = 1
links['CA']['business']['http://rss.canada.com/get/?F7477'] = 1
links['CA']['business']['http://rss.canada.com/get/?F6939'] = 1
links['CA']['business']['http://blogs.wsj.com/canadarealtime/feed/?mod=WSJ_Canada_Realtime&mg=blogswsj&url=http%253A%252F%252Fblogs.wsj.com%252Fcanadarealtime%252Ffeed%253Fmod%253DWSJ_Canada_Realtime'] = 1
links['CA']['gaming']['http://rss.canada.com/get/?F7541'] = 1
links['CA']['gaming']['http://feeds.feedburner.com/feedburner/g4tv_ca'] = 1
links['CA']['gaming']['http://cogconnected.com/feed/'] = 1
links['CA']['gaming']['http://www.cvawards.ca/feed/'] = 1
links['CA']['gaming']['http://www.gamingpost.ca/feed/'] = 1
links['CA']['health']['http://rss.canada.com/get/?F7523'] = 1
links['CA']['health']['http://rss.canada.com/get/?F7519'] = 1
links['CA']['health']['http://rss.canada.com/get/?F7517'] = 1
links['CA']['health']['http://www.ellecanada.com/rss_feed/home.rss'] = 1
links['CA']['health']['http://news.gc.ca/web/fd-en.do?mthd=thm&ft=atom&crtr.thm1D=9'] = 1
links['CA']['health']['http://www.journaldemontreal.com/jm/sante/rss.xml'] = 1
links['CA']['health']['http://www.calgarysun.com/life/rss.xml'] = 1
links['CA']['health']['http://www.huffingtonpost.ca/feeds/verticals/canada-lifestyle/index.xml'] = 1
links['CA']['health']['http://rss.canoe.com/Lifewise/home.xml'] = 1
links['CA']['health']['http://feeds.bbci.co.uk/news/world/us_and_canada/rss.xml'] = 1
links['CA']['health']['http://www.thestar.com/feeds.articles.life.health_wellness.rss'] = 1
links['CA']['health']['http://www.theglobeandmail.com/life/health-and-fitness/?service=rss'] = 1
links['CA']['health']['http://www.torontosun.com/life/health-and-fitness/rss.xml'] = 1
links['CA']['health']['http://rss.canada.com/get/?F7523'] = 1
links['CA']['health']['http://news.nationalpost.com/category/health/feed/'] = 1
links['CA']['health']['http://rss.canada.com/get/?F6918'] = 1
links['CA']['health']['http://ottawacitizen.com/feed'] = 1
links['CA']['health']['http://rss.canada.com/get/?F7738'] = 1
links['CA']['health']['http://rss.metroland.com/9/article/hamilton/living/health'] = 1
links['CA']['science']['http://www.cbc.ca/cmlink/1.392'] = 1
links['CA']['science']['http://rss.radio-canada.ca/fils/nouvelles/scienceetsante.xml'] = 1
links['CA']['science']['http://www.cbc.ca/cmlink/1.392'] = 1
links['CA']['science']['http://www.ctvnews.ca/rss/ctvnews-ca-sci-tech-public-rss-1.822295'] = 1
links['CA']['science']['http://globalnews.ca/science/feed/'] = 1
links['CA']['science']['http://www.huffingtonpost.com/feeds/verticals/science/index.xml'] = 1
links['CA']['science']['http://www.thestar.com/feeds.articles.life.technology.rss'] = 1
links['CA']['science']['http://business.financialpost.com/category/fp-tech-desk/feed/'] = 1
links['CA']['science']['http://news.nationalpost.com/category/health/feed/'] = 1
links['CA']['science']['http://www.theglobeandmail.com/technology/?service=rss'] = 1
links['CA']['science']['http://www.torontosun.com/tech/rss.xml'] = 1
links['CA']['science']['http://www.torontosun.com/life/health-and-fitness/rss.xml'] = 1
links['CA']['science']['http://rss.canada.com/get/?F7523'] = 1
links['CA']['sports']['http://rss.canada.com/get/?F255'] = 1
links['CA']['sports']['http://www.journaldemontreal.com/sports/rss.xml'] = 1
links['CA']['sports']['http://rss.radio-canada.ca/fils/sports/sports.xml'] = 1
links['CA']['sports']['http://www.calgarysun.com/sports/rss.xml'] = 1
links['CA']['sports']['http://www.huffingtonpost.ca/feeds/verticals/canada-sports/index.xml'] = 1
links['CA']['sports']['http://rss.canoe.com/Slam/home.xml'] = 1
links['CA']['sports']['http://torontosportsmedia.com/feed'] = 1
links['CA']['sports']['http://en.cis-sic.ca/landing/headlines-featured?feed=rss_2.0'] = 1
links['CA']['sports']['http://www.cbc.ca/cmlink/rss-sports'] = 1
links['CA']['sports']['http://www.tsn.ca/datafiles/rss/Stories.xml'] = 1
links['CA']['sports']['http://www.sportsnet.ca/feed/'] = 1
links['CA']['sports']['https://ca.sports.yahoo.com/top/rss.xml'] = 1
links['CA']['sports']['http://www.thestar.com/feeds.articles.sports.rss'] = 1
links['CA']['sports']['http://www.theglobeandmail.com/sports/?service=rss'] = 1
links['CA']['sports']['http://rss.canada.com/get/?F260'] = 1
links['CA']['sports']['http://globalnews.ca/sports/feed/'] = 1
links['CA']['sports']['http://www.torontosun.com/sports/rss.xml'] = 1
links['CA']['sports']['http://www.winnipegfreepress.com/rss/?path=%2Fsports'] = 1
links['CA']['tech']['http://rss.canada.com/get/?F7539'] = 1
links['CA']['tech']['http://rss.radio-canada.ca/fils/nouvelles/technologie.xml'] = 1
links['CA']['tech']['http://www.calgarysun.com/tech/rss.xml'] = 1
links['CA']['tech']['http://www.pcauthority.com.au/RSS/rss.ashx?type=Category&ID=12'] = 1
links['CA']['tech']['http://www.techvibes.com/feed/blog/xml/global/'] = 1
links['CA']['tech']['http://betakit.com/feed/'] = 1
links['CA']['tech']['http://www.cbc.ca/cmlink/rss-technology'] = 1
links['CA']['tech']['http://rss.canada.com/get/?F7166'] = 1
links['CA']['tech']['http://rss.canada.com/get/?F221'] = 1
links['CA']['tech']['http://rss.canada.com/get/?F7484'] = 1
links['CA']['tech']['http://mobilesyrup.com/feed/'] = 1
links['CA']['tech']['http://globalnews.ca/tech/feed/'] = 1
links['CA']['tech']['http://www.thestar.com/feeds.articles.life.technology.rss'] = 1
links['CA']['tech']['http://www.theepochtimes.com/n3/c/tech/tech-news/feed/'] = 1
links['CA']['tech']['http://www.huffingtonpost.com/feeds/verticals/technology/news.xml'] = 1
links['CA']['tech']['http://feeds.reuters.com/reuters/technologyNews?format=xml'] = 1
links['CA']['entertainment']['http://rss.canada.com/get/?F7502'] = 1
links['CA']['entertainment']['http://www.ellecanada.com/rss_feed/celebrity.rss'] = 1
links['CA']['entertainment']['http://www.calgarysun.com/entertainment/celebrities/rss.xml'] = 1
links['CA']['entertainment']['http://rss.canoe.com/Jam/Celebrities/home.xml'] = 1
links['CA']['entertainment']['http://blogs.etcanada.com/feed/'] = 1
links['CA']['entertainment']['http://www.hgtv.ca/rss.ashx'] = 1
links['CA']['entertainment']['http://syndication.eonline.com/syndication/feeds/rssfeeds/topstories.xml?edition=ca'] = 1
links['CA']['entertainment']['http://www.laineygossip.com/Rss'] = 1
links['CA']['entertainment']['http://www.thestar.com/feeds.articles.entertainment.rss'] = 1
links['CA']['entertainment']['http://www.huffingtonpost.ca/feeds/verticals/canada-music/index.xml'] = 1
links['CA']['entertainment']['http://news.gc.ca/web/fd-en.do?mthd=thm&ft=atom&crtr.thm1D=13'] = 1
links['CA']['entertainment']['http://www.calgarysun.com/entertainment/music/rss.xml'] = 1
links['CA']['entertainment']['http://rss.canoe.com/Jam/Music/home.xml'] = 1
links['CA']['entertainment']['http://feeds.feedburner.com/ExclaimCaAllArticles'] = 1
links['CA']['entertainment']['http://www.chartattack.com/feed/'] = 1
links['CA']['entertainment']['http://musiccanada.com/feed/'] = 1
links['CA']['entertainment']['http://www.blogtalkradio.com/canadianmusician/podcast'] = 1
links['CA']['entertainment']['http://feeds.feedburner.com/thescenemag'] = 1
links['CA']['entertainment']['http://rss.canada.com/get/?F6946'] = 1
links['CA']['entertainment']['http://rss.canada.com/get/?F7500'] = 1
links['CA']['entertainment']['http://www.journaldemontreal.com/spectacles/rss.xml'] = 1
links['CA']['entertainment']['http://rss.radio-canada.ca/fils/arts-spectacles/artsetspectacles.xml'] = 1
links['CA']['entertainment']['http://www.calgarysun.com/entertainment/rss.xml'] = 1
links['CA']['entertainment']['http://rss.canoe.com/Jam/Movies/home.xml'] = 1
links['CA']['entertainment']['http://rss.cbc.ca/lineup/arts.xml'] = 1
links['CA']['entertainment']['http://arts.nationalpost.com/category/arts/feed/'] = 1
links['CA']['entertainment']['http://rss.canada.com/get/?F69'] = 1
links['CA']['entertainment']['http://www.theglobeandmail.com/arts/?service=rss'] = 1
links['CA']['entertainment']['http://www.torontosun.com/entertainment/rss.xml'] = 1
links['CA']['entertainment']['http://globalnews.ca/category/entertainment/feed/'] = 1
links['CA']['entertainment']['http://rss.canada.com/get/?F6948'] = 1
links['CA']['entertainment']['http://www.ottawasun.com/entertainment/rss.xml'] = 1
links['CA']['entertainment']['http://rss.canada.com/get/?F7366'] = 1
links['CA']['entertainment']['http://rss.canoe.ca/Jam/home.xml'] = 1
links['CA']['entertainment']['http://www.dose.ca/feed'] = 1
links['IN']['general']['http://www.telegraphindia.com/feeds/rss.jsp?id=3'] = 1
links['IN']['general']['http://www.caravanmagazine.in/feed'] = 1
links['IN']['general']['http://thewire.in/feed/'] = 1
links['IN']['general']['http://www.oneindia.com/rss/news-india-fb.xml'] = 1
links['IN']['general']['http://sify.com/rss2/news/article/category/national'] = 1
links['IN']['general']['http://www.tehelka.com/?feed=custom_feed'] = 1
links['IN']['general']['http://www.outlookindia.com/rss/main/website'] = 1
links['IN']['general']['http://www.outlookindia.com/rss/main/newswire'] = 1
links['IN']['general']['http://www.outlookindia.com/rss/section/19'] = 1
links['IN']['general']['http://feeds.hindustantimes.com/HT-India'] = 1
links['IN']['general']['http://indianexpress.com/section/india/feed/'] = 1
links['IN']['general']['http://timesofindia.feedsportal.com/c/33039/f/533916/index.rss'] = 1
links['IN']['general']['http://feeds.bbci.co.uk/news/world/asia/india/rss.xml'] = 1
links['IN']['general']['http://ibnlive.in.com/ibnrss/top.xml'] = 1
links['IN']['general']['http://timesofindia.feedsportal.com/c/33039/f/533965/index.rss'] = 1
links['IN']['general']['http://indiatoday.feedsportal.com/c/33614/f/589699/index.rss'] = 1
links['IN']['general']['http://www.thehindubusinessline.com/news/?service=rss'] = 1
links['IN']['general']['http://www.thehindubusinessline.com/news/international/?service=rss'] = 1
links['IN']['general']['http://www.thehindu.com/news/national/?service=rss'] = 1
links['IN']['general']['http://zeenews.india.com/rss/world-news.xml'] = 1
links['IN']['general']['http://www.business-standard.com/rss/current-affairs-news-11501.rss'] = 1
links['IN']['general']['http://nvonews.com/feed/'] = 1
links['IN']['general']['http://economictimes.indiatimes.com/News/rssfeeds/1715249553.cms'] = 1
links['IN']['general']['http://www.sikhsiyasat.com/feed/'] = 1
links['IN']['general']['http://indiatoday.feedsportal.com/c/33614/f/589699/index.rss'] = 1
links['IN']['general']['http://www.asianage.com/rss/38'] = 1
links['IN']['general']['http://www.business-standard.com/rss/home_page_top_stories.rss'] = 1
links['IN']['general']['http://www.dnaindia.com/rss.xml'] = 1
links['IN']['general']['http://www.deccanchronicle.com/rss.xml'] = 1
links['IN']['general']['http://www.deccanherald.com/rss-internal/top-stories.rss'] = 1
links['IN']['general']['http://syndication.financialexpress.com/rss/latest-news.xml'] = 1
links['IN']['general']['http://www.mid-day.com/Resources/midday/rss/news-national.xml'] = 1
links['IN']['general']['http://www.livemint.com/rss/homepage'] = 1
links['IN']['politics']['http://www.telegraphindia.com/feeds/rss.jsp?id=4'] = 1
links['IN']['politics']['http://sify.com/rss2/news/article/category/politics'] = 1
links['IN']['politics']['http://www.thehindu.com/news/national/?service=rss'] = 1
links['IN']['politics']['http://www.thehindu.com/news/international/south-asia/?service=rss'] = 1
links['IN']['politics']['http://www.thehindu.com/news/cities/?service=rss'] = 1
links['IN']['politics']['https://in.news.yahoo.com/rss/politics'] = 1
links['IN']['politics']['https://in.news.yahoo.com/rss/national'] = 1
links['IN']['politics']['http://ibnlive.in.com/ibnrss/rss/politics/politics.xml'] = 1
links['IN']['politics']['http://ibnlive.in.com/ibnrss/rss/politics/elections.xml'] = 1
links['IN']['politics']['http://ibnlive.in.com/ibnrss/rss/shows/facethenation.xml'] = 1
links['IN']['politics']['http://ibnlive.in.com/ibnrss/rss/elections/delhielections.xml'] = 1
links['IN']['politics']['http://ibnlive.in.com/ibnrss/rss/elections/chhattisgarhelections.xml'] = 1
links['IN']['politics']['http://ibnlive.in.com/ibnrss/rss/loksabhaelections/loksabhaelections.xml'] = 1
links['IN']['politics']['http://ibnlive.in.com/ibnrss/rss/elections/madhyapradeshelections.xml'] = 1
links['IN']['politics']['http://ibnlive.in.com/ibnrss/rss/elections/rajasthanelections.xml'] = 1
links['IN']['politics']['http://ibnlive.in.com/ibnrss/rss/elections/mizoramelections.xml'] = 1
links['IN']['politics']['http://ibnlive.in.com/ibnrss/rss/elections/haryanaelections.xml'] = 1
links['IN']['politics']['http://ibnlive.in.com/ibnrss/rss/elections/maharashtraelections.xml'] = 1
links['IN']['politics']['http://ibnlive.in.com/ibnrss/rss/elections/odishaelections.xml'] = 1
links['IN']['politics']['http://ibnlive.in.com/ibnrss/rss/elections/andhrapradeshelections.xml'] = 1
links['IN']['politics']['http://ibnlive.in.com/ibnrss/rss/elections/sikkimelections.xml'] = 1
links['IN']['politics']['http://inp.sagepub.com/rss/current.xml'] = 1
links['IN']['politics']['http://indianexpress.com/section/india/politics/feed/'] = 1
links['IN']['politics']['http://timesofindia.feedsportal.com/c/33039/f/533916/index.rss'] = 1
links['IN']['politics']['http://www.ft.com/rss/world/asiapacific/india'] = 1
links['IN']['politics']['http://www.firstpost.com/politics/feed'] = 1
links['IN']['politics']['http://www.frontline.in/politics/?service=rss'] = 1
links['IN']['politics']['http://www.economist.com/topics/india/index.xml'] = 1
links['IN']['politics']['http://www.livemint.com/rss/economy_politics'] = 1
links['IN']['business']['http://www.oneindia.com/rss/news-business-fb.xml'] = 1
links['IN']['business']['http://www.tehelka.com/economy/?feed=custom_feed'] = 1
links['IN']['business']['http://www.outlookindia.com/rss/section/18'] = 1
links['IN']['business']['http://sify.com/rss2/business/article/category/bank'] = 1
links['IN']['business']['http://sify.com/rss2/business/article/category/ipo'] = 1
links['IN']['business']['http://timesofindia.feedsportal.com/c/33039/f/534010/index.rss'] = 1
links['IN']['business']['http://timesofindia.feedsportal.com/c/33039/f/533919/index.rss'] = 1
links['IN']['business']['http://economictimes.indiatimes.com/rssfeedsdefault.cms'] = 1
links['IN']['business']['http://www.businessweek.com/feeds/most-popular.rss'] = 1
links['IN']['business']['http://feeds.reuters.com/reuters/INbusinessNews'] = 1
links['IN']['business']['http://www.business-standard.com/rss/todays-paper.rss'] = 1
links['IN']['business']['http://www.business-standard.com/rss/home_page_top_stories.rss'] = 1
links['IN']['business']['http://forbesindia.com/rssfeed/rss_all.xml'] = 1
links['IN']['business']['http://feeds.feedburner.com/NDTV-Business?format=xml'] = 1
links['IN']['business']['http://feeds.hindustantimes.com/HT-Business?format=xml'] = 1
links['IN']['business']['http://zeenews.india.com/rss/business.xml'] = 1
links['IN']['business']['https://in.news.yahoo.com/rss//india'] = 1
links['IN']['business']['http://hosted.ap.org/lineups/WORLDHEADS.rss'] = 1
links['IN']['business']['http://www.huffingtonpost.com/feeds/verticals/business/news.xml'] = 1
links['IN']['business']['http://www.livemint.com/rss/homepage'] = 1
links['IN']['business']['http://www.nytimes.com/services/xml/rss/nyt/InternationalBusiness.xml'] = 1
links['IN']['business']['https://news.google.com/news/feeds?cf=all&ned=in&hl=en&topic=b&output=rss'] = 1
links['IN']['business']['http://www.thetimes.co.uk/tto/business/markets/india/rss'] = 1
links['IN']['business']['http://www.livemint.com/rss/companies'] = 1
links['IN']['business']['http://www.livemint.com/rss/consumer'] = 1
links['IN']['business']['http://www.livemint.com/rss/money'] = 1
links['IN']['business']['http://www.livemint.com/rss/industry'] = 1
links['IN']['health']['http://www.femina.in/feeds/feeds-lifestyle.xml'] = 1
links['IN']['health']['http://www.femina.in/feeds/feeds-fitness.xml'] = 1
links['IN']['health']['http://feeds.hindustantimes.com/HT-HomePage-TopStories'] = 1
links['IN']['health']['http://timesofindia.indiatimes.com/rssfeeds/2886714.cms'] = 1
links['IN']['health']['http://feeds.bbci.co.uk/news/world/asia/rss.xml'] = 1
links['IN']['health']['http://indiatoday.intoday.in/rss/homepage-topstories.jsp'] = 1
links['IN']['health']['http://lifestyle.in.msn.com/rss/health.aspx'] = 1
links['IN']['health']['http://www.thehealthsite.com/comments/feed/'] = 1
links['IN']['health']['http://www.mensxp.com/feeds.xml'] = 1
links['IN']['health']['http://forbesindia.com/rssfeed/rss_life.xml'] = 1
links['IN']['health']['http://www.mansworldindia.com/feed/'] = 1
links['IN']['health']['http://www.thehindu.com/sci-tech/health/?service=rss'] = 1
links['IN']['gaming']['http://www.pcquest.com/rss-2-2/?cat_slug=games'] = 1
links['IN']['science']['http://feeds.feedburner.com/NDTV-Tech'] = 1
links['IN']['science']['http://sify.com/rss2/news/article/category/science'] = 1
links['IN']['science']['http://www.thehindu.com/sci-tech/science/?service=rss'] = 1
links['IN']['science']['http://feeds.hindustantimes.com/HT-Reviews'] = 1
links['IN']['science']['http://www.dnaindia.com/feeds/scitech.xml'] = 1
links['IN']['science']['http://www.business-standard.com/rss/technology-108.rss'] = 1
links['IN']['science']['http://www.indodaily.com/indodaily.xml'] = 1
links['IN']['science']['http://timesofindia.indiatimes.com/rss.cms'] = 1
links['IN']['science']['http://zeenews.india.com/rss/science-technology-news.xml'] = 1
links['IN']['science']['http://indianexpress.com/technology/feed/'] = 1
links['IN']['sports']['http://www.telegraphindia.com/feeds/rss.jsp?id=7'] = 1
links['IN']['sports']['http://www.espncricinfo.com/rss/content/story/feeds/6.xml'] = 1
links['IN']['sports']['http://live-feeds.cricbuzz.com/CricbuzzFeed'] = 1
links['IN']['sports']['http://www.oneindia.com/rss/news-sports-fb.xml'] = 1
links['IN']['sports']['http://www.outlookindia.com/rss/section/22'] = 1
links['IN']['sports']['http://sify.com/rss2/sports/article/category/cricket'] = 1
links['IN']['sports']['http://sify.com/rss2/sports/article/category/football'] = 1
links['IN']['sports']['http://sify.com/rss2/sports/article/category/others'] = 1
links['IN']['sports']['http://timesofindia.feedsportal.com/c/33039/f/533921/index.rss'] = 1
links['IN']['sports']['http://feeds.feedburner.com/NDTV-Sports'] = 1
links['IN']['sports']['http://feeds.feedburner.com/NDTV-Cricket'] = 1
links['IN']['sports']['http://syndication.indianexpress.com/rss/785/latest-news.xml'] = 1
links['IN']['sports']['https://in.news.yahoo.com/rss/sports'] = 1
links['IN']['sports']['http://indiatoday.feedsportal.com/c/33614/f/589706/index.rss?http://indiatoday.intoday.in/rss/article.jsp?sid=84'] = 1
links['IN']['sports']['http://zeenews.india.com/rss/sports-news.xml'] = 1
links['IN']['sports']['http://feeds.reuters.com/reuters/worldOfSport'] = 1
links['IN']['sports']['http://feeds.hindustantimes.com/HT-Sport'] = 1
links['IN']['sports']['http://www.thehindu.com/sport/?service=rss'] = 1
links['IN']['sports']['http://www.abplive.in/sports/?widgetName=rssfeed&widgetContentId=101313&getXmlFeed=true'] = 1
links['IN']['tech']['http://www.pcquest.com/rss-2-2/?cat_slug=news-launches'] = 1
links['IN']['tech']['http://www.pcquest.com/rss-2-2/?cat_slug=tech-&-trends'] = 1
links['IN']['tech']['http://sify.com/rss2/business/article/category/technology'] = 1
links['IN']['tech']['http://timesofindia.feedsportal.com/c/33039/f/533923/index.rss'] = 1
links['IN']['tech']['http://www.techtree.com/rss.xml'] = 1
links['IN']['tech']['http://indianexpress.com/section/technology/feed/'] = 1
links['IN']['tech']['http://www.thehindu.com/sci-tech/?service=rss'] = 1
links['IN']['tech']['http://www.thehindu.com/sci-tech/technology/?service=rss'] = 1
links['IN']['tech']['http://feeds.hindustantimes.com/HT-Technology'] = 1
links['IN']['tech']['http://syndication.financialexpress.com/rss/377/tech.xml'] = 1
links['IN']['tech']['http://www.gizmodo.in/rss_section_feeds/19124814.cms'] = 1
links['IN']['tech']['http://zeenews.india.com/rss/science-technology-news.xml'] = 1
links['IN']['tech']['http://www.computerworld.in/rss.xml'] = 1
links['IN']['entertainment']['http://www.telegraphindia.com/feeds/rss.jsp?id=20'] = 1
links['IN']['entertainment']['http://www.tehelka.com/cinema/?feed=custom_feed'] = 1
links['IN']['entertainment']['http://rollingstoneindia.com/feed/'] = 1
links['IN']['entertainment']['http://www.filmibeat.com/rss/filmibeat-fb.xml'] = 1
links['IN']['entertainment']['http://www.outlookindia.com/rss/section/23'] = 1
links['IN']['entertainment']['http://www.tellychakkar.com/rss.xml'] = 1
links['IN']['entertainment']['http://www.in.com/ - sthash.XTJcCE91.dpuf'] = 1
links['IN']['entertainment']['http://feeds2.feedburner.com/musicmaza/zNyY'] = 1
links['IN']['entertainment']['http://feeds2.feedburner.com/BollywoodNewsFeed'] = 1
links['IN']['entertainment']['http://www.bollywoodnewsworld.com/feed'] = 1
links['IN']['entertainment']['http://www.bollywood.com/rss.xml'] = 1
links['IN']['entertainment']['http://timesofindia.indiatimes.com/rssfeeds/1081479906.cms'] = 1
links['IN']['entertainment']['http://indianexpress.com/entertainment/feed/'] = 1
links['IN']['entertainment']['http://www.bollywoodlife.com/feed/'] = 1
links['IN']['entertainment']['http://www.bollywoodhungama.com/rss/news.xml'] = 1
links['IN']['entertainment']['http://www.dnaindia.com/feeds/entertainment.xml'] = 1
links['IN']['entertainment']['http://zeenews.india.com/rss/india-national-news.xml'] = 1
links['IN']['entertainment']['http://feeds.reuters.com/reuters/INentertainmentNews'] = 1
links['IN']['entertainment']['http://feeds.hindustantimes.com/HT-Entertainment'] = 1
links['IN']['entertainment']['http://www.thehindu.com/entertainment/?service=rss'] = 1
links['IN']['entertainment']['http://www.livemint.com/rss/lounge'] = 1
links['IN']['kerala']['http://english.manoramaonline.com/tag-result-page.ManoramaOnline~English@news@News@Latest-News@rss.html'] = 1
links['IN']['kerala']['https://www.thehindu.com/news/national/kerala/feeder/default.rss'] = 1
links['IN']['kerala']['https://english.manoramaonline.com/news/kerala.html'] = 1
links['IN']['kerala']['https://timesofindia.indiatimes.com/topic/Kerala-edition'] = 1
links['IN']['kerala']['http://www.newindianexpress.com/States/Kerala/rssfeed/?id=178&getXmlFeed=true'] = 1
links['GB']['general']['http://www.theguardian.com/observer/rss'] = 1
links['GB']['general']['http://www.theguardian.com/world/rss'] = 1
links['GB']['general']['http://www.theweek.co.uk/feeds/all'] = 1
links['GB']['general']['http://feeds.bbci.co.uk/news/world/rss.xml'] = 1
links['GB']['general']['http://feeds.bbci.co.uk/news/uk/rss.xml'] = 1
links['GB']['general']['http://www.theguardian.com/uk/rss'] = 1
links['GB']['general']['http://news.sky.com/feeds/rss/uk.xml'] = 1
links['GB']['general']['http://www.telegraph.co.uk/news/uknews/rss'] = 1
links['GB']['general']['http://www.ft.com/rss/world/uk'] = 1
links['GB']['general']['http://www.standard.co.uk/news/rss'] = 1
links['GB']['general']['http://www.oxfordmail.co.uk/news/rss/'] = 1
links['GB']['general']['http://www.dailymail.co.uk/news/index.rss'] = 1
links['GB']['general']['http://rss.feedsportal.com/c/266/f/3503/index.rss'] = 1
links['GB']['general']['http://rss.feedsportal.com/c/266/f/3496/index.rss'] = 1
links['GB']['general']['http://feeds.feedburner.com/daily-express-uk-news'] = 1
links['GB']['general']['http://www.standard.co.uk/news/rss'] = 1
links['GB']['general']['http://www.manchestereveningnews.co.uk/rss.xml'] = 1
links['GB']['general']['http://www.itv.com/news/index.rss'] = 1
links['GB']['general']['http://www.thecourier.co.uk/cmlink/1.67998'] = 1
links['GB']['general']['http://feeds.feedburner.com/ScottishNewsHeraldScotland'] = 1
links['GB']['general']['http://www.channel4.com/news/uk/rss'] = 1
links['GB']['general']['http://www.scotsman.com/rss/cmlink/1.65668'] = 1
links['GB']['general']['http://www.newsletter.co.uk/rss/cmlink/1.1571541'] = 1
links['GB']['general']['http://feeds.examiner.ie/ietopstories'] = 1
links['GB']['general']['http://www.irishtimes.com/rss/editors-picks-feed-1.1904962?localLinksEnabled=false'] = 1
links['GB']['politics']['http://feeds.skynews.com/feeds/rss/politics.xml'] = 1
links['GB']['politics']['http://www.ft.com/rss/world/uk/politics'] = 1
links['GB']['politics']['http://www.scotsman.com.dynamic.feedsportal.com/pf/610141/www.scotsman.com/rss/cmlink/1.3942672'] = 1
links['GB']['politics']['http://www.independent.co.uk/news/people/diary/'] = 1
links['GB']['politics']['http://feeds.bbci.co.uk/news/politics/rss.xml'] = 1
links['GB']['politics']['http://feeds.theguardian.com/theguardian/politics/rss'] = 1
links['GB']['politics']['http://www.telegraph.co.uk/news/politics/rss'] = 1
links['GB']['politics']['http://mf.feeds.reuters.com/reuters/UKdomesticNews'] = 1
links['GB']['politics']['http://www.economist.com/blogs/blighty/index.xml'] = 1
links['GB']['politics']['http://www.economist.com/feeds/print-sections/76/britain.xml'] = 1
links['GB']['politics']['http://www.economist.com/topics/european-union/index.xml'] = 1
links['GB']['politics']['http://www.huffingtonpost.co.uk/news/british-national-party/feed/'] = 1
links['GB']['politics']['http://www.huffingtonpost.co.uk/news/london-riots/feed/'] = 1
links['GB']['politics']['http://www.huffingtonpost.com/tag/uk-election/feed'] = 1
links['GB']['politics']['http://www.huffingtonpost.co.uk/news/immigration/feed/'] = 1
links['GB']['politics']['http://www.huffingtonpost.co.uk/news/islam/feed/'] = 1
links['GB']['politics']['http://www.huffingtonpost.co.uk/news/media/feed/'] = 1
links['GB']['politics']['http://www.huffingtonpost.co.uk/news/terrorism/feed/'] = 1
links['GB']['politics']['http://www.huffingtonpost.co.uk/news/space-agency/feed/'] = 1
links['GB']['politics']['http://www.huffingtonpost.co.uk/news/economy/feed/'] = 1
links['GB']['politics']['http://www.standard.co.uk/news/politics/rss'] = 1
links['GB']['business']['http://www.economist.com/sections/business-finance/rss.xml'] = 1
links['GB']['business']['https://uk.finance.yahoo.com/news/provider-yahoofinance/?format=rss'] = 1
links['GB']['business']['http://www.theweek.co.uk/taxonomy/term/60/feed'] = 1
links['GB']['business']['http://feeds.feedburner.com/daily-express-finance-news'] = 1
links['GB']['business']['http://www.manchestereveningnews.co.uk/business/rss.xml'] = 1
links['GB']['business']['http://online.wsj.com/xml/rss/3_7031.xml'] = 1
links['GB']['business']['http://blogs.wsj.com/moneybeat/category/europe/feed/?mod=WSJ_moneybeat_blog'] = 1
links['GB']['business']['http://feeds.theguardian.com/theguardian/uk/business/rss'] = 1
links['GB']['business']['http://feeds.bbci.co.uk/news/business/rss.xml'] = 1
links['GB']['business']['http://mf.feeds.reuters.com/reuters/UKVideoBusiness'] = 1
links['GB']['business']['http://news.sky.com/feeds/rss/business.xml'] = 1
links['GB']['business']['http://rss.feedsportal.com/c/266/f/3510/index.rss'] = 1
links['GB']['business']['http://www.telegraph.co.uk/finance/rss'] = 1
links['GB']['business']['http://www.thetimes.co.uk/tto/business/rss'] = 1
links['GB']['business']['http://www.ibtimes.co.uk/rss/uk'] = 1
links['GB']['business']['http://www.ft.com/rss/home/europe'] = 1
links['GB']['business']['http://blogs.wsj.com/emergingeurope/feed/?mod=emergingeurope&mg=blogswsj&url=http%253A%252F%252Fblogs.wsj.com%252Femergingeurope%252Ffeed%253Fmod%253Demergingeurope'] = 1
links['GB']['gaming']['http://www.eurogamer.net/?format=rss'] = 1
links['GB']['gaming']['http://www.theguardian.com/technology/games/rss'] = 1
links['GB']['gaming']['http://feeds.feedburner.com/daily-star-Gaming'] = 1
links['GB']['gaming']['http://metro.co.uk/entertainment/gaming/feed/'] = 1
links['GB']['gaming']['http://www.economist.com/sections/business-finance/rss.xml'] = 1
links['GB']['health']['http://www.theguardian.com/us/lifeandstyle/rss'] = 1
links['GB']['health']['http://www.theguardian.com/lifeandstyle/health-and-wellbeing/rss'] = 1
links['GB']['health']['http://www.theguardian.com/fashion/rss'] = 1
links['GB']['health']['http://www.theguardian.com/travel/rss'] = 1
links['GB']['health']['http://feeds.bbci.co.uk/news/health/rss.xml'] = 1
links['GB']['health']['http://www.independent.co.uk/life-style/health-and-families/health-news/rss'] = 1
links['GB']['health']['http://www.express.co.uk/posts/rss/11/health'] = 1
links['GB']['health']['http://www.thetimes.co.uk/tto/health/rss'] = 1
links['GB']['health']['http://www.huffingtonpost.com/feeds/verticals/uk-lifestyle/index.xml'] = 1
links['GB']['health']['http://www.standard.co.uk/lifestyle/rss'] = 1
links['GB']['health']['http://feeds.bbci.co.uk/news/uk/rss.xml'] = 1
links['GB']['health']['http://www.telegraph.co.uk/health/rss'] = 1
links['GB']['health']['http://www.dailymail.co.uk/health/index.rss'] = 1
links['GB']['health']['http://www.ok.co.uk/rss/health'] = 1
links['GB']['health']['http://www.hellomagazine.com/rss.xml'] = 1
links['GB']['health']['http://www.mynaturallifestyle.co.uk/naturallifestyle/feed/'] = 1
links['GB']['health']['http://www.candis.co.uk/feed/'] = 1
links['GB']['health']['http://www.soarmagazine.co.uk/feed/'] = 1
links['GB']['science']['http://www.theguardian.com/uk/environment/rss'] = 1
links['GB']['science']['http://www.economist.com/sections/science-technology/rss.xml'] = 1
links['GB']['science']['https://www.newscientist.com/feed/home'] = 1
links['GB']['science']['http://feeds.theguardian.com/theguardian/science/rss'] = 1
links['GB']['science']['http://feeds.bbci.co.uk/news/science_and_environment/rss.xml'] = 1
links['GB']['science']['http://www.independent.co.uk/news/science/rss'] = 1
links['GB']['science']['http://www.wired.co.uk/news/rss'] = 1
links['GB']['science']['http://www.telegraph.co.uk/science/science-news/rss'] = 1
links['GB']['science']['http://www.theregister.co.uk/science/headlines.atom'] = 1
links['GB']['science']['http://www.dailymail.co.uk/sciencetech/articles.rss'] = 1
links['GB']['science']['http://www.mirror.co.uk/news/technology-science/rss.xml'] = 1
links['GB']['science']['http://www.ibtimes.co.uk/rss/science'] = 1
links['GB']['science']['http://www.in.com/rss/news/sci-tech'] = 1
links['GB']['sports']['http://www.theguardian.com/football/rss'] = 1
links['GB']['sports']['http://www.theweek.co.uk/feeds/sport'] = 1
links['GB']['sports']['http://feeds.feedburner.com/daily-express-sport-news'] = 1
links['GB']['sports']['http://www.mirror.co.uk/sport/rss.xml'] = 1
links['GB']['sports']['http://feeds.feedburner.com/SportcoukNewsRssFeed'] = 1
links['GB']['sports']['http://www.standard.co.uk/sport/football/rss'] = 1
links['GB']['sports']['http://www.skysports.com/rss/0,20514,12040,00.xml'] = 1
links['GB']['sports']['http://www.skysports.com/rss/0,20514,20876,00.xml'] = 1
links['GB']['sports']['http://feeds.theguardian.com/theguardian/uk/sport/rss'] = 1
links['GB']['sports']['http://feeds.bbci.co.uk/sport/0/rss.xml?edition=uk'] = 1
links['GB']['sports']['http://www.dailymail.co.uk/sport/index.rss'] = 1
links['GB']['sports']['http://www.huffingtonpost.co.uk/feeds/verticals/uk-sport/index.xml'] = 1
links['GB']['sports']['http://www.telegraph.co.uk/sport/rss'] = 1
links['GB']['sports']['http://metro.co.uk/sport/feed/'] = 1
links['GB']['sports']['http://rss.feedsportal.com/c/266/f/3784/index.rss'] = 1
links['GB']['sports']['https://uk.eurosport.yahoo.com/eurosport/tickerdb/sport/0.xml'] = 1
links['GB']['sports']['http://mf.feeds.reuters.com/reuters/UKSportsNews'] = 1
links['GB']['tech']['http://feeds.feedburner.com/uk/gizmodo'] = 1
links['GB']['tech']['http://feeds.skynews.com/feeds/rss/technology.xml'] = 1
links['GB']['tech']['http://rss.feedsportal.com/c/559/f/7174/index.rss'] = 1
links['GB']['tech']['http://www.huffingtonpost.co.uk/feeds/verticals/uk-tech/index.xml'] = 1
links['GB']['tech']['http://techcrunch.com/europe/feed/'] = 1
links['GB']['tech']['http://www.techrepublic.com/rssfeeds/blog/european-technology/'] = 1
links['GB']['tech']['http://feeds.theguardian.com/theguardian/technology/rss'] = 1
links['GB']['tech']['http://feeds.bbci.co.uk/news/technology/rss.xml#'] = 1
links['GB']['tech']['http://blogs.technet.com/b/uktechnet/rss.aspx'] = 1
links['GB']['tech']['http://blogs.which.co.uk/technology/feed/atom/'] = 1
links['GB']['tech']['http://feeds.webservice.techradar.com/rss/new'] = 1
links['GB']['entertainment']['http://syndication.eonline.com/syndication/feeds/rssfeeds/topstories.xml?edition=uk'] = 1
links['GB']['entertainment']['http://www.express.co.uk/posts/rss/79/showbiznews'] = 1
links['GB']['entertainment']['http://metro.co.uk/entertainment/showbiz/feed/'] = 1
links['GB']['entertainment']['http://feeds.skynews.com/feeds/rss/entertainment.xml'] = 1
links['GB']['entertainment']['http://www.celebsnow.co.uk/feed'] = 1
links['GB']['entertainment']['http://www.huffingtonpost.co.uk/news/celebrity/feed/'] = 1
links['GB']['entertainment']['http://www.standard.co.uk/showbiz/rss'] = 1
links['GB']['entertainment']['http://www.manchestereveningnews.co.uk/news/showbiz-news/rss.xml'] = 1
links['GB']['entertainment']['http://www.theguardian.com/music/rss'] = 1
links['GB']['entertainment']['http://www.music-news.com/rss/UK/news'] = 1
links['GB']['entertainment']['http://feeds.feedburner.com/factmag'] = 1
links['GB']['entertainment']['http://www.uncut.co.uk/feed'] = 1
links['GB']['entertainment']['http://www.clashmusic.com/rss.xml'] = 1
links['GB']['entertainment']['http://www.theguardian.com/us/film/rss'] = 1
links['GB']['entertainment']['http://www.mirror.co.uk/tv/tv-news/rss.xml'] = 1
links['GB']['entertainment']['http://www.film-news.co.uk/rss/UK/news'] = 1
links['GB']['entertainment']['https://uk.movies.yahoo.com/rss'] = 1
links['GB']['entertainment']['http://ukfilmnews.com/?feed=rss2'] = 1
links['GB']['entertainment']['http://www.bfi.org.uk/latest/feed'] = 1
links['GB']['entertainment']['http://metro.co.uk/entertainment/tv/feed/'] = 1
links['GB']['entertainment']['http://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml'] = 1
links['GB']['entertainment']['http://www.telegraph.co.uk/culture/culturenews/rss'] = 1
links['GB']['entertainment']['http://www.huffingtonpost.com/feeds/verticals/uk-entertainment/index.xml'] = 1
links['GB']['entertainment']['http://celebrity.uk.msn.com/RSS-Celebrity-Gossip.aspx'] = 1
links['GB']['entertainment']['http://tv.uk.msn.com/blog/editor-rss.aspx'] = 1
links['GB']['entertainment']['http://www.popsugar.co.uk/celebrity/feed'] = 1
links['GB']['entertainment']['http://www.entertainmentnews.co.uk/feed/'] = 1
links['GB']['entertainment']['http://www.independent.co.uk/arts-entertainment/tv/rss'] = 1
links['GB']['entertainment']['http://www.dailymail.co.uk/tvshowbiz/articles.rss'] = 1
links['GB']['entertainment']['http://www.mtv.co.uk/rss/news'] = 1
links['GB']['entertainment']['http://www.ok.co.uk/rss/entertainment'] = 1
links['GB']['entertainment']['http://www.hellomagazine.com/rss.xml'] = 1
links['GB']['entertainment']['http://feeds.feedburner.com/the-edge-susu'] = 1
links['GB']['entertainment']['http://www.bestdaily.co.uk/rss/zones/gb/all.xml'] = 1
links['GB']['entertainment']['http://www.tntmagazine.com/entertainment/rss'] = 1
links['GB']['entertainment']['http://www.reveal.co.uk/rss/zones/gb/all.xml'] = 1
links['GB']['entertainment']['http://www.qthemusic.com/feed/'] = 1
links['GB']['entertainment']['http://feeds2.feedburner.com/nmecom/rss/newsxml'] = 1
links['GB']['entertainment']['http://www.theguardian.com/tv-and-radio/entertainment/rss'] = 1
links['AU']['general']['http://www.abc.net.au/news/feed/46182/rss.xml'] = 1
links['AU']['general']['http://feeds.feedburner.com/TheAustralianTheNationNews'] = 1
links['AU']['general']['http://feeds.smh.com.au/rssheadlines/national.xml'] = 1
links['AU']['general']['http://www.theguardian.com/au/rss'] = 1
links['AU']['general']['http://www.abc.net.au/local/rss/sydney/news.xml'] = 1
links['AU']['general']['http://www.channelnewsasia.com/starterkit/servlet/cna/rss/asiapacific.xml'] = 1
links['AU']['general']['http://feeds.brisbanetimes.com.au/rssheadlines/national.xml'] = 1
links['AU']['general']['http://feeds.brisbanetimes.com.au/rssheadlines/world.xml'] = 1
links['AU']['general']['http://feeds.theage.com.au/rssheadlines/national.xml'] = 1
links['AU']['general']['http://au.ibtimes.com/rss/articles/countries/13.rss'] = 1
links['AU']['general']['http://rss.nzherald.co.nz/rss/xml/nzhrsscid_000000002.xml'] = 1
links['AU']['general']['http://www.gmanetwork.com/news/rss/news'] = 1
links['AU']['general']['http://feeds.bbci.co.uk/news/world/asia/rss.xml'] = 1
links['AU']['general']['http://www.dailymail.co.uk/auhome/index.rss'] = 1
links['AU']['general']['http://feeds.feedburner.com/dailytelegraphnationalnewsndm?format=xml'] = 1
links['AU']['general']['http://feeds.news.com.au/public/rss/2.0/bcm_top_stories_257.xml'] = 1
links['AU']['general']['http://feeds.news.com.au/public/rss/2.0/anow_topstories_250.xml'] = 1
links['AU']['general']['http://feeds.news.com.au/heraldsun/rss/heraldsun_news_morenews_2794.xml'] = 1
links['AU']['general']['http://feeds.news.com.au/public/rss/2.0/The%20Mercury%20%7C%20Top%20Stories_3304.xml'] = 1
links['AU']['general']['http://feeds.news.com.au/public/rss/2.0/wtn_top_3368.xml'] = 1
links['AU']['politics']['http://feeds.feedburner.com/TheAustralianPolitics'] = 1
links['AU']['politics']['http://feeds.news.com.au/public/rss/2.0/au_national_affairs_news_13_3296.xml'] = 1
links['AU']['politics']['http://feeds.feedburner.com/TheAustralianMediaNews'] = 1
links['AU']['politics']['http://www.businessspectator.com.au/bs/rss.xml'] = 1
links['AU']['politics']['http://www.abc.net.au/news/feed/1534/rss.xml'] = 1
links['AU']['politics']['http://www.abc.net.au/radionational/feed/3727018/rss.xml'] = 1
links['AU']['politics']['http://www.abc.net.au/radionational/feed/2884582/rss.xml'] = 1
links['AU']['politics']['http://www.pm.gov.au/rss-feeds/press-office'] = 1
links['AU']['politics']['http://www.rba.gov.au/rss/rss-cb-media-releases.xml'] = 1
links['AU']['politics']['http://www.crikey.com.au/politics/feed'] = 1
links['AU']['politics']['http://www.economist.com/topics/australia/index.xml'] = 1
links['AU']['politics']['http://www.theguardian.com/world/australian-politics/rss'] = 1
links['AU']['politics']['http://mashable.com/category/australian-politics/rss/'] = 1
links['AU']['business']['http://www.businessspectator.com.au/bs/rss.xml'] = 1
links['AU']['business']['http://www.cio.com/index.rss'] = 1
links['AU']['business']['http://www.dynamicbusiness.com.au/feed'] = 1
links['AU']['business']['http://feeds.feedburner.com/TheAustralianBusNews?format=xml'] = 1
links['AU']['business']['http://feeds.feedburner.com/TheAustralianBusAviation?format=xml'] = 1
links['AU']['business']['http://feeds.feedburner.com/TheAustralianBusinessWorldBusNews?format=xml'] = 1
links['AU']['business']['http://feeds.news.com.au/public/rss/2.0/business_top_stories_346.xml'] = 1
links['AU']['business']['http://www.abc.net.au/news/feed/51892/rss.xml'] = 1
links['AU']['business']['http://www.smh.com.au/rssheadlines/business.xml'] = 1
links['AU']['business']['http://feeds.news.com.au/heraldsun/rss/heraldsun_news_business_2783.xml'] = 1
links['AU']['business']['http://abns.com.au/feed/'] = 1
links['AU']['health']['http://www.smh.com.au/rssheadlines/health/article/rss.xml'] = 1
links['AU']['health']['http://www.womenshealthandfitness.com.au/component/obrss/women-s-health-fitnesscombined-feed?format='] = 1
links['AU']['health']['http://feeds.news.com.au/public/rss/2.0/news_lifestyle_3171.xml'] = 1
links['AU']['health']['http://www.telegraph.co.uk/health/rss'] = 1
links['AU']['health']['http://www.shapemagazine.com.au/feed/'] = 1
links['AU']['health']['http://www.alive.com/articles/rss'] = 1
links['AU']['health']['http://www.wellbeing.com.au/blog/feed/'] = 1
links['AU']['health']['http://www.mensfitnessmagazine.com.au/topics/health-nutrition/feed/'] = 1
links['AU']['health']['http://www.dailyrecord.co.uk/lifestyle/health-fitness/rss.xml'] = 1
links['AU']['health']['http://www.starobserver.com.au/category/features/healthy-living/feed'] = 1
links['AU']['science']['http://feeds.news.com.au/public/rss/2.0/news_tech_506.xml'] = 1
links['AU']['science']['http://www.smh.com.au/rssheadlines/health/article/rss.xml'] = 1
links['AU']['science']['http://www.sbs.com.au/news/rss/news/science-technology.xml'] = 1
links['AU']['science']['http://www.theage.com.au/rssheadlines/technology-news/article/rss.xml'] = 1
links['AU']['science']['http://www.watoday.com.au/rssheadlines/technology-news/article/rss.xml'] = 1
links['AU']['science']['http://www.australianscience.com.au/feed/'] = 1
links['AU']['science']['http://www.scienceweek.net.au/homepage/feed/'] = 1
links['AU']['sports']['http://feeds.news.com.au/public/rss/2.0/fs_breaking_news_13.xml'] = 1
links['AU']['sports']['http://www.abc.net.au/news/feed/45924/rss.xml'] = 1
links['AU']['sports']['http://feeds.feedburner.com/TheAustralianSportsNews'] = 1
links['AU']['sports']['http://feeds.news.com.au/public/rss/2.0/news_sport_3168.xml'] = 1
links['AU']['sports']['http://feeds.smh.com.au/rssheadlines/sport.xml'] = 1
links['AU']['sports']['http://feeds.theage.com.au/rssheadlines/sport.xml'] = 1
links['AU']['sports']['http://feeds.news.com.au/rss/newslocal/dt_nlocal_sport_3214.xml'] = 1
links['AU']['sports']['http://feeds.news.com.au/heraldsun/rss/heraldsun_news_sport_2789.xml'] = 1
links['AU']['sports']['http://feeds.bbci.co.uk/sport/0/cricket/rss.xml?edition=uk'] = 1
links['AU']['sports']['http://sbs.feedsportal.com/c/34692/f/637526/index.rss'] = 1
links['AU']['sports']['http://wwos.ninemsn.com.au/rss/headlines/'] = 1
links['AU']['tech']['http://feeds.gizmodo.com.au/gizmodoaustraliaau'] = 1
links['AU']['tech']['http://www.smh.com.au/rssheadlines/technology-news/article/rss.xml'] = 1
links['AU']['tech']['http://feeds.news.com.au/public/rss/2.0/ausit_exec_topstories_385.xml'] = 1
links['AU']['tech']['http://feeds.news.com.au/heraldsun/rss/heraldsun_news_technology_2790.xml'] = 1
links['AU']['tech']['http://feeds.news.com.au/public/rss/2.0/news_tech_506.xml'] = 1
links['AU']['tech']['http://techau.com.au/feed/'] = 1
links['AU']['tech']['http://www.techrepublic.com/rssfeeds/blog/australian-technology/'] = 1
links['AU']['entertainment']['http://feeds.smh.com.au/rssheadlines/entertainment.xml'] = 1
links['AU']['entertainment']['http://www.news.com.au/entertainment'] = 1
links['AU']['entertainment']['http://feeds.news.com.au/public/rss/2.0/cpost_news_entertainment_3329.xml'] = 1
links['AU']['entertainment']['http://feeds.news.com.au/public/rss/2.0/The%20Mercury%20|%20Entertainment_3306.xml'] = 1
links['AU']['entertainment']['http://www.goldcoastbulletin.com.au/entertainment'] = 1
links['AU']['entertainment']['http://www.spotlightreport.net/feed'] = 1
links['AU']['entertainment']['http://www.popsugar.com.au/celebrity/feed'] = 1
links['AU']['entertainment']['http://www.okmagazine.com.au/rss.axd?channel=entertainment_articles'] = 1
links['AU']['entertainment']['http://www.studiotv.com.au/feed/'] = 1
links['AU']['entertainment']['http://feeds.feedburner.com/sunshinecoastdailyentertainmen'] = 1


